### ISSUE TITLE
HEIC files did not convert to JPG as expected

### ISSUE THREAD

**Issue by Pulinski** [jakemanger/howtoconvert-support#102]
**Describe the bug**
HEIC files did not convert to JPG as expected.

**To Reproduce**
Drag files files into HowToConvert and convert to JPG. No adjustments to settings

**Expected behavior**
Expected 7 JPG files created

macOS 15.5
How To Convert v1.1.4

Log File

Original file paths: 
/Users/paul/Downloads/r/20250721_233338798_iOS.heic, /Users/paul/Downloads/r/20250721_233357067_iOS.heic, /Users/paul/Downloads/r/20250721_233419429_iOS.heic, /Users/paul/Downloads/r/20250721_233441346_iOS.heic, /Users/paul/Downloads/r/20250721_233458292_iOS.heic, /Users/paul/Downloads/r/20250721_233516476_iOS.heic, /Users/paul/Downloads/r/20250721_233559314_iOS.heic
File 1: 20250721_233338798_iOS.heic (2.64 MB)
File 2: 20250721_233357067_iOS.heic (1.77 MB)
File 3: 20250721_233419429_iOS.heic (1.73 MB)
File 4: 20250721_233441346_iOS.heic (2.04 MB)
File 5: 20250721_233458292_iOS.heic (2.56 MB)
File 6: 20250721_233516476_iOS.heic (2.45 MB)
File 7: 20250721_233559314_iOS.heic (2.37 MB)
=== Converting files from original paths: ===
20250721_233338798_iOS.heic - Original path: /Users/paul/Downloads/r/20250721_233338798_iOS.heic
20250721_233357067_iOS.heic - Original path: /Users/paul/Downloads/r/20250721_233357067_iOS.heic
20250721_233419429_iOS.heic - Original path: /Users/paul/Downloads/r/20250721_233419429_iOS.heic
20250721_233441346_iOS.heic - Original path: /Users/paul/Downloads/r/20250721_233441346_iOS.heic
20250721_233458292_iOS.heic - Original path: /Users/paul/Downloads/r/20250721_233458292_iOS.heic
20250721_233516476_iOS.heic - Original path: /Users/paul/Downloads/r/20250721_233516476_iOS.heic
20250721_233559314_iOS.heic - Original path: /Users/paul/Downloads/r/20250721_233559314_iOS.heic
[20250721_233338798_iOS.heic] Original file path: /Users/paul/Downloads/r/20250721_233338798_iOS.heic
[20250721_233357067_iOS.heic] Original file path: /Users/paul/Downloads/r/20250721_233357067_iOS.heic
[20250721_233419429_iOS.heic] Original file path: /Users/paul/Downloads/r/20250721_233419429_iOS.heic
[20250721_233338798_iOS.heic] Using original file path: /Users/paul/Downloads/r/20250721_233338798_iOS.heic
[20250721_233357067_iOS.heic] Using original file path: /Users/paul/Downloads/r/20250721_233357067_iOS.heic
[20250721_233419429_iOS.heic] Using original file path: /Users/paul/Downloads/r/20250721_233419429_iOS.heic
[20250721_233338798_iOS.heic] Created temporary output file: /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-fddb3794-024c-4da8-b77d-d570acbba4fd.jpg
[20250721_233338798_iOS.heic] Local ImageMagick: converting 20250721_233338798_iOS.heic -> 20250721_233338798_iOS.jpg
[20250721_233338798_iOS.heic] Local ImageMagick command: magick /Users/paul/Downloads/r/20250721_233338798_iOS.heic /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-fddb3794-024c-4da8-b77d-d570acbba4fd.jpg
[20250721_233357067_iOS.heic] Created temporary output file: /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-8d946142-b603-45cf-8783-1d5b36707713.jpg
[20250721_233357067_iOS.heic] Local ImageMagick: converting 20250721_233357067_iOS.heic -> 20250721_233357067_iOS.jpg
[20250721_233357067_iOS.heic] Local ImageMagick command: magick /Users/paul/Downloads/r/20250721_233357067_iOS.heic /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-8d946142-b603-45cf-8783-1d5b36707713.jpg
[20250721_233419429_iOS.heic] Created temporary output file: /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-d5e5ce41-aa4f-4ac7-bcb9-5533d580f7b8.jpg
[20250721_233419429_iOS.heic] Local ImageMagick: converting 20250721_233419429_iOS.heic -> 20250721_233419429_iOS.jpg
[20250721_233419429_iOS.heic] Local ImageMagick command: magick /Users/paul/Downloads/r/20250721_233419429_iOS.heic /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-d5e5ce41-aa4f-4ac7-bcb9-5533d580f7b8.jpg
[20250721_233419429_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233357067_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233357067_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233357067_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233338798_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233357067_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233419429_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233419429_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233357067_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233419429_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233338798_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233419429_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233419429_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233338798_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233357067_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233338798_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233338798_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233338798_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233357067_iOS.heic] Error: magick exited with code Some(1): 
[20250721_233419429_iOS.heic] Error: magick exited with code Some(1): 
[20250721_233338798_iOS.heic] Error: magick exited with code Some(1): 
[20250721_233441346_iOS.heic] Original file path: /Users/paul/Downloads/r/20250721_233441346_iOS.heic
[20250721_233458292_iOS.heic] Original file path: /Users/paul/Downloads/r/20250721_233458292_iOS.heic
[20250721_233516476_iOS.heic] Original file path: /Users/paul/Downloads/r/20250721_233516476_iOS.heic
[20250721_233441346_iOS.heic] Using original file path: /Users/paul/Downloads/r/20250721_233441346_iOS.heic
[20250721_233458292_iOS.heic] Using original file path: /Users/paul/Downloads/r/20250721_233458292_iOS.heic
[20250721_233516476_iOS.heic] Using original file path: /Users/paul/Downloads/r/20250721_233516476_iOS.heic
[20250721_233441346_iOS.heic] Created temporary output file: /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-bfaef228-70f9-4ba1-ab6d-d68fa06b6500.jpg
[20250721_233441346_iOS.heic] Local ImageMagick: converting 20250721_233441346_iOS.heic -> 20250721_233441346_iOS.jpg
[20250721_233441346_iOS.heic] Local ImageMagick command: magick /Users/paul/Downloads/r/20250721_233441346_iOS.heic /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-bfaef228-70f9-4ba1-ab6d-d68fa06b6500.jpg
[20250721_233458292_iOS.heic] Created temporary output file: /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-670a2543-0e82-4fa1-befd-430d64965378.jpg
[20250721_233458292_iOS.heic] Local ImageMagick: converting 20250721_233458292_iOS.heic -> 20250721_233458292_iOS.jpg
[20250721_233458292_iOS.heic] Local ImageMagick command: magick /Users/paul/Downloads/r/20250721_233458292_iOS.heic /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-670a2543-0e82-4fa1-befd-430d64965378.jpg
[20250721_233516476_iOS.heic] Created temporary output file: /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-cc11511d-632a-4ce1-b39a-ff2f7c08fff3.jpg
[20250721_233516476_iOS.heic] Local ImageMagick: converting 20250721_233516476_iOS.heic -> 20250721_233516476_iOS.jpg
[20250721_233516476_iOS.heic] Local ImageMagick command: magick /Users/paul/Downloads/r/20250721_233516476_iOS.heic /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-cc11511d-632a-4ce1-b39a-ff2f7c08fff3.jpg
[20250721_233516476_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233441346_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233441346_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233441346_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233458292_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233441346_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233516476_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233458292_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233441346_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233458292_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233458292_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233458292_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233516476_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233516476_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233441346_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233516476_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233458292_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233516476_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233441346_iOS.heic] Error: magick exited with code Some(1): 
[20250721_233458292_iOS.heic] Error: magick exited with code Some(1): 
[20250721_233516476_iOS.heic] Error: magick exited with code Some(1): 
[20250721_233559314_iOS.heic] Original file path: /Users/paul/Downloads/r/20250721_233559314_iOS.heic
[20250721_233559314_iOS.heic] Using original file path: /Users/paul/Downloads/r/20250721_233559314_iOS.heic
[20250721_233559314_iOS.heic] Created temporary output file: /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-a1077aa1-b765-40dc-b970-a529395dd2bc.jpg
[20250721_233559314_iOS.heic] Local ImageMagick: converting 20250721_233559314_iOS.heic -> 20250721_233559314_iOS.jpg
[20250721_233559314_iOS.heic] Local ImageMagick command: magick /Users/paul/Downloads/r/20250721_233559314_iOS.heic /var/folders/xj/_1pw_5jn34n7frc78jkzq4nh0000gn/T/tauri-temp-a1077aa1-b765-40dc-b970-a529395dd2bc.jpg
[20250721_233559314_iOS.heic] magick: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/Users/paul/Downloads/r/20250721_233559314_iOS.heic' @ error/heic.c/IsHEIFSuccess/144.
[20250721_233559314_iOS.heic] Error: magick exited with code Some(1):

**Comment by jakemanger** [comment]
Hi Pulinski,

Thanks for the detailed log. It makes solving these so much easier.

I believe this issue is fixed in the latest release.
Could you:
1) Go to [https://howtoconvert.co/signin](https://howtoconvert.co/signin)

2) Download and install the latest release

3) In the app, go to Settings > Support More Formats > Next to Core tools > Clear Installation > Download Core Tools

4) Hit next until finished and then try and convert again


If that doesn't work, would you be able to send through a test file, either here or to jake@howtoconvert.co

The clear and download steps should update the magick tool to a new version that supports the latest HEIC

Hope that solves your issue!

**Comment by Pulinski** [comment]
Jake,

v1.1.5 didn't convert these files. Standard iPhone images (of my faulty LG OLED TV)

[Archive.zip](https://github.com/user-attachments/files/21357717/Archive.zip)

Paul

**Comment by jakemanger** [comment]
Hi Paul,

Just tested those and they are converting fine on my end.

Again, could you try reinstalling the Core tools?

Hit Settings

<img width="614" height="297" alt="Image" src="https://github.com/user-attachments/assets/158051c6-351d-42bd-9172-36cd717541fe" />

Support More Formats

<img width="361" height="173" alt="Image" src="https://github.com/user-attachments/assets/ec6cb2d9-2de6-4f24-a6dc-b6b44cd165ca" />

The purple next arrow

<img width="246" height="213" alt="Image" src="https://github.com/user-attachments/assets/68502e4e-097d-4d5b-bc7b-0624c5546357" />

The yellow Clear Installation button

<img width="437" height="243" alt="Image" src="https://github.com/user-attachments/assets/c4ae62b2-64dc-4119-877a-9a670c84be1e" />

Then the Download Core Tools Button

<img width="495" height="201" alt="Image" src="https://github.com/user-attachments/assets/d60e4101-1ac4-4077-82c2-a6a124935e33" />

You should see  Magick Version: ImageMagick 7.1.1-44 Q16-HDRI aarch64 22688 https://imagemagick.org
like so 

<img width="802" height="286" alt="Image" src="https://github.com/user-attachments/assets/23f04693-f756-4c96-b436-d3e61ac00398" />

Then hit the purple next arrow until you finish

**Comment by Pulinski** [comment]
I followed your instructions but still have a different ImageMagick version.

<img width="800" height="156" alt="Image" src="https://github.com/user-attachments/assets/e7642554-62c5-420f-865b-5d365dbd3932" />

Paul

**Comment by jakemanger** [comment]
That's quite odd. Sorry about this issue. It is highly unusual, so I am trying to figure out the cause at the moment. 

Do you have imagemagick installed for other uses? It could be that How to Convert is auto detecting another version that is already installed on your computer.

Here is something to try:
1) Click "Custom Installation Paths"

<img width="924" height="167" alt="Image" src="https://github.com/user-attachments/assets/b954e6c1-7fe0-498a-9e4f-bf6841b355d8" />

2) Click "Select Magick Location"

<img width="487" height="174" alt="Image" src="https://github.com/user-attachments/assets/645e52e6-dc1f-4943-b792-689689a06920" />

When you see the finder menu pop up, type the "~" symbol (you need Shift to add ~)

Then type out "~/.howtoconvert/magick/bin/magick" like so

<img width="976" height="555" alt="Image" src="https://github.com/user-attachments/assets/1a749fae-c09a-42fe-b46f-dc67397688e4" />

If that doesn't work, then another option is to

1) Open Finder

2) Select Go > Go to Folder

<img width="687" height="486" alt="Image" src="https://github.com/user-attachments/assets/9c4e0f34-7d0a-4ee8-91ad-aae11a88e7d7" />

3) Type in "~/.howtoconvert/" and press Enter

<img width="907" height="422" alt="Image" src="https://github.com/user-attachments/assets/cc333acd-d6d2-4257-b896-95a21428a51b" />

4) Delete everything in here

<img width="861" height="344" alt="Image" src="https://github.com/user-attachments/assets/aa390e39-48e8-4855-8d08-79611bad2721" />

5) Go back to How to Convert and re-download the core tools

<img width="829" height="257" alt="Image" src="https://github.com/user-attachments/assets/b3353325-25c8-4ed4-9077-c02206f05211" />

**Comment by Pulinski** [comment]
I think we are getting closer to the answer. I deleted the directories but they are still being detected. I must have these utilities in use for other programs in a common directory.

Paul

**Comment by jakemanger** [comment]
Hi Pulinski,

Good to hear. I realise these steps are getting quite cumbersome and I want you to know that I am happy to refund you if this gets too much and you can't get it to work.

If they are still being detected after deletion, then perhaps you are right and the utilities are being detected from other programs.

I think the first test would be to fully Quit How to Convert with CMD + Q and then redo the Download Core Tools step, then just test a file.


If we're still getting the same error, then we can test whether magick is installed elsewhere, but it will involve using the command line.

1) Open Terminal 
An easy way is to click CMD + Space to open Spotlight and then Search for Terminal 

2) Once open, type in `which magick`

<img width="566" height="320" alt="Image" src="https://github.com/user-attachments/assets/2c915218-79ec-4e2e-9471-b27713e63eef" />

If text like this appears, then magick is already installed. If it says "command not found" or something along those lines, then it isn't installed.

If you see "homebrew" anywhere in there like above, you can update that version with

```
brew upgrade imagemagick
```

If it's somewhere else and you don't use it for anything (something may have installed it a while ago), then you can remove that version with:
```
sudo rm -f $(which magick)
```

**Comment by Pulinski** [comment]
I went to the second half of your email and did those steps

Here is a screenshot. Definately installed by homebrew and up-to-date.

<img width="692" height="187" alt="Image" src="https://github.com/user-attachments/assets/14a0ad16-4e78-40f0-b4a1-8d7c4d622006" />

I am going to do a full uninstall and reinstall of HTC.

Paul

**Comment by Pulinski** [comment]
A complete uninstall and a reinstall of all the core services has fixed the issue.

<img width="799" height="87" alt="Image" src="https://github.com/user-attachments/assets/2873082b-832d-4c37-93b4-b69949b1fe98" />

It does appear that the later version of imagemagick is the issue. This might be a problem that pops up again for you.

Paul

**Comment by jakemanger** [comment]
Fantastic to hear, @Pulinski 

Sorry about the difficulty again. I'll add some features to make diagnosing these kinds of issues easier. Really appreciate your patience!
